package org.ungs.core.observability.metrics.api;

public enum MetricType {
  AVG_DELIVERY_TIME,
  WINDOWED_DELIVERY_TIME,
  P95_DELIVERY_TIME, // TODO
  PACKETS_IN_FLIGHT, // TODO
  QUEUE_LENGTH, // TODO
  AVG_DELIVERY_TIME_VS_LOAD_LEVEL,
  AVG_DELIVERY_TIME_VS_LOAD_LEVEL_VS_TICK,
}
